# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task: compilewithsyncimport
      - task: compilewithoutsyncimport
    silent: false
    ignore_error: true

  compilewithsyncimport:
    desc: Compile example with sync import
    cmds:
      - go build -o /dev/null ./cmd/withsync
  
  compilewithoutsyncimport:
    desc: Compile example without sync import
    cmds:
      - go build -o /dev/null ./cmd/withoutsync